[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]

[phases.install]
cmds = [
    "pip install --break-system-packages -r requirements.txt",
    "python -m pip list | grep uvicorn || echo 'WARNING: uvicorn not found'"
]

[start]
cmd = "python -m uvicorn main:app --host 0.0.0.0 --port $PORT"