[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]

[phases.install]
cmds = [
    "pip install --break-system-packages -r requirements.txt",
    "python -c 'import uvicorn; print(f\"uvicorn installed: {uvicorn.__version__}\")'",
    "python -c 'import fastapi; print(f\"fastapi installed: {fastapi.__version__}\")'",
    "ls -la start.py"
]

[start]
cmd = "python start.py"

[variables]
PYTHONUNBUFFERED = "1"