[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "gcc"]

[phases.install]
cmds = ["python3.11 -m pip install --break-system-packages --upgrade pip", "python3.11 -m pip install --break-system-packages -r requirements.txt"]

[start]
cmd = "python3.11 -m uvicorn main:app --host 0.0.0.0 --port $PORT"

[variables]
NIXPACKS_NO_DEFAULT_START_CMD = "true"
NIXPACKS_NO_PYTHON_AUTOSTART = "true"